version: '3.7'

services:
  microservice:
    build:
      context: .
      dockerfile: my.dockerfile
    image: airelavmi/distrib:microservice_lr3
    ports:
      - "5000:5000"
    networks:
      - monitoring  # Подключаем к сети monitoring

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring  # Подключаем к сети monitoring

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring  # Подключаем к сети monitoring

networks:
  monitoring:  # Определяем сеть monitoring
