version: '3.8'

services:
  microservice:
    build: .
    ports:
      - "5000:5000"  # Пробрасываем порт Flask
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"  # Пробрасываем порт Grafana
    depends_on:
      - prometheus
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Подключаем файл конфигурации Prometheus
    ports:
      - "9090:9090"  # Пробрасываем порт Prometheus
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
